name: room_expenses
description: Shared room expense tracker
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.0
  firebase_auth: ^4.17.0

flutter:
  uses-material-design: true
